export const RECORD_USER_PROFILE = 'RECORD_USER_PROFILE'
export const RECORD_USER_PLAYLIST = 'RECORD_USER_PLAYLIST'
export const RECORD_USER_FM = 'RECORD_USER_FM'
export const RECORD_TOP_LIST = 'RECORD_TOP_LIST'
export const RECORD_BANNER = 'RECORD_BANNER'

